#!/bin/zsh

if ! type fzf >/dev/null 2>&1; then
  if [[ -n $TMUX ]]; then
    local msg='selector-init: command not found: fzf'
    tmux split-window "less <<< \"$msg\""
  fi
  return 1
fi

if [[ -n $1 ]]; then
  BUFFER="$1 "
  CURSOR=$#BUFFER
  zle reset-prompt
fi
