#!/bin/zsh

local selector='fzf'

if type tmux fzf-tmux >/dev/null 2>&1 && [[ ${FZF_TMUX:-0} != 0 ]]; then
  selector='fzf-tmux'
fi

cat | $selector $@ >! $FZF_WIDGETS_CACHE

if [[ $? = 130 ]]; then
  selector-clear
  return 1
elif [[ -z `cat $FZF_WIDGETS_CACHE` ]]; then
  if [[ -n $TMUX ]]; then
    local msg="selector-exec: there's no match"
    tmux split-window "less <<< \"$msg\""
  fi
  selector-clear
  return 1
fi
