#!/bin/zsh

IFS=$'\n' private -a items=(`cat $FZF_WIDGETS_CACHE`)
if [[ -n $items ]]; then
  for item in $items; do RBUFFER+="$item:q " done
  CURSOR=$#RBUFFER
fi

if [[ -n $BUFFER ]] && [[ -n $1 ]]; then
  RBUFFER+="$1"
  CURSOR=$#RBUFFER
fi

if [[ -n $BUFFER ]] && [[ -n $items || -n $1 ]]; then
  zle -R -c
  zle accept-line
fi
