#!/bin/zsh

local -A selector
selector[cmd]='fzf'

if type tmux fzf-tmux >/dev/null 2>&1 && [[ $FZF_WIDGET_TMUX != 0 ]]; then
  selector[cmd]='fzf-tmux'
fi

cat | $selector[cmd] $@

selector[status]=$?
echo "$selector[status]" >! $FZF_WIDGET_CACHE/status
[[ $selector[status] = 0 ]] && return 0 || return 1
