#!/bin/zsh

local selector='fzf'

if type tmux fzf-tmux >/dev/null 2>&1 && [[ $FZF_WIDGET_TMUX != 0 ]]; then
  selector='fzf-tmux'
fi

cat | $selector $@ >! $FZF_WIDGET_CACHE

if [[ $? = 130 ]]; then
  __fzf::widget::clear
  return 1
elif [[ -z `cat $FZF_WIDGET_CACHE` ]]; then
  if [[ -n $TMUX ]]; then
    local msg="$0: there's no match"
    tmux split-window "less <<< \"$msg\""
  fi
  __fzf::widget::clear
  return 1
fi
