#!/bin/zsh

local -a items
IFS=$'\n' items=(`cat $FZF_WIDGETS_CACHE`)
if [[ -n $items ]]; then
  for item in $items; do RBUFFER+="$item:q:gs/\\~/~/ " done
  CURSOR=$#RBUFFER
fi

if [[ -n $BUFFER ]] && [[ -n $1 ]]; then
  RBUFFER+="$1"
  CURSOR=$#RBUFFER
fi

if [[ -n $BUFFER ]] && [[ -n $items || -n $1 ]]; then
  zle reset-prompt
  zle accept-line
fi
