#!/bin/zsh

__fzf::widget::init 'cd --' || return 1

find . -mindepth 1 -type d -o -type l | \
  sed 's|\./||g' | \
  __fzf::widget::select $FZF_WIDGET_OPTS[change-dir] +m | \
  __fzf::widget::insert -q

__fzf::widget::exec
