#!/bin/zsh

if [[ -z $DOT_BASE_DIR ]]; then
  __fzf::widget::print 'fzf-edit-dotfiles: Not set $DOT_BASE_DIR'
  return 1
fi

__fzf::widget::init "$EDITOR --" || return 1

git -C $DOT_BASE_DIR ls-files | \
  sed "s|^|~/|g" | \
  __fzf::widget::select $FZF_WIDGET_OPTS[edit-dotfiles] -m | \
  __fzf::widget::insert -q

__fzf::widget::exec
