#!/bin/zsh

selector-init

ls $FZF_WIDGETS_ROOT/autoload/widgets/ | \
  sed -e 's/fzf-//g' | \
  egrep -v '^select-widget$' | \
  selector-select $FZF_WIDGETS_OPTS[select-widget] +m

selector-filter "sed 's/^/fzf-/'"

selector-exec
