#!/bin/zsh

__fzf::widget::init 'docker image rm'

docker image ls | \
  sed 1d | \
  __fzf::widget::select $FZF_WIDGET_OPTS[docker-remove-images] -m

__fzf::widget::filter "awk '{print \$3}'"

__fzf::widget::insert
