#!/bin/zsh

if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  if [[ -n $TMUX ]]; then
    private msg='fzf-git-add: Not a git repository'
    tmux split-window "less <<< \"$msg\""
  fi
  return 1
fi

selector-init 'git add --'

private base_path="`git rev-parse --show-cdup | sed 's%/%\\/%g'`"

git status --porcelain | \
  sed "s/^\(..\) /\1\t${base_path}/" | \
  grep "^.[MD?]" | \
  selector-select -m

selector-filter "awk '{print \$2}'"

selector-insert
