#!/bin/zsh

__fzf::widget::init || return 1

fc -l 1 | \
  __fzf::widget::select --tac --tiebreak=index \
  --bind=ctrl-r:toggle-sort $FZF_WIDGET_OPTS[insert-history] --query="$LBUFFER" +m | \
  sed 's/ *[0-9]*  //g' | \
  __fzf::widget::replace
