#!/bin/zsh

__fzf::widget::init 'kill'

ps -u $USER -o pid,stat,cputime,command | \
  sed 1d | \
  __fzf::widget::select $FZF_WIDGETS_OPTS[kill-process] -m

__fzf::widget::filter "awk '{print \$1}'"

__fzf::widget::insert
