#!/bin/zsh

__fzf::widget::init 'docker container stop'

docker container ls | \
  sed 1d | \
  __fzf::widget::select $FZF_WIDGETS_OPTS[docker-stop-containers] -m

__fzf::widget::filter "awk '{print \$1}'"

__fzf::widget::insert
