#!/bin/zsh

selector-init 'git add --'

private base_path="`git rev-parse --show-cdup | sed 's%/%\\/%g'`"

git status --porcelain | \
  sed "s/^\(..\) /\1\t${base_path}/" | \
  grep "^.[MD?]" | \
  selector-select -m

selector-cat | awk '{print $2}' | selector-save

selector-insert
