#!/bin/zsh

__fzf::widget::init 'docker container start'

docker container ls -a | \
  sed 1d | \
  __fzf::widget::select $FZF_WIDGET_OPTS[docker-start-containers] -m

__fzf::widget::filter "awk '{print \$1}'"

__fzf::widget::insert
