#!/bin/zsh

selector-init

fc -l 1 | selector-select --tac --tiebreak=index --bind=ctrl-r:toggle-sort $FZF_WIDGETS_OPTS[insert-history] --query="$LBUFFER" +m

items=(`cat $FZF_WIDGETS_CACHE`)
if [[ -n $items ]]; then
  num=$items[1]
  if [ -n "$num" ]; then
    zle vi-fetch-history -n $num
  fi
fi
