#!/bin/zsh

selector-init 'ssh --'

cat ~/.ssh/config /etc/ssh/ssh_config 2>/dev/null | \
  grep -i '^host' | \
  grep -v '*' | \
  awk '{if (length($2) > 0) {print $2}}' | \
  sort -u | \
  selector-select $FZF_WIDGETS_OPTS[exec-ssh] +m

selector-insert
