#!/bin/zsh

__fzf::widget::init 'docker container rm'

docker container ls -a | \
  sed 1d | \
  __fzf::widget::select $FZF_WIDGETS_OPTS[docker-remove-containers] -m

__fzf::widget::filter "awk '{print \$1}'"

__fzf::widget::insert
