#!/bin/zsh

if [[ -z $DOT_BASE_DIR ]]; then
  if [[ -n $TMUX ]]; then
    local msg='fzf-edit-dotfiles: Not set \$DOT_BASE_DIR'
    tmux split-window "less <<< \"$msg\""
  fi
  return 1
fi

selector-init "$EDITOR --"

git -C $DOT_BASE_DIR ls-files | \
  sed "s|^|~/|g" | \
  selector-select $FZF_WIDGETS_OPTS[edit-dotfiles] -m

selector-insert
