#!/bin/zsh

if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  if [[ -n $TMUX ]]; then
    local msg='fzf-git-delete-branches: Not a git repository'
    tmux split-window "less <<< \"$msg\""
  fi
  return 1
fi

__fzf::widget::init 'git branch -D'

git branch --list -v | \
  grep -v '^\*' | \
  sed 's/^  *//' | \
  __fzf::widget::select $FZF_WIDGETS_OPTS[git-delete-branches] -m

__fzf::widget::filter "awk '{print \$1}'"

__fzf::widget::insert
