#!/bin/zsh

selector-init "$EDITOR --"

private -a dirs
dirs=(
  `echo "$DOT_DIRS" | sed -e 's/:/\n/g' | sed -e "s|^|$DOT_HOME/|g"`
)

find $dirs -type f -o -type l | selector-select -m

selector-insert
