#!/bin/zsh

selector-init 'docker container rm'

docker container ls -a | \
  sed 1d | \
  selector-select $FZF_WIDGETS_OPTS[docker-remove-containers] -m

selector-filter "awk '{print \$1}'"

selector-insert
