#!/bin/zsh

__fzf::widget::init 'docker container logs'

docker container ls -a | \
  sed 1d | \
  __fzf::widget::select $FZF_WIDGET_OPTS[docker-logs-container] +m

__fzf::widget::filter "awk '{print \$1}'"

__fzf::widget::insert
