#!/bin/zsh

__fzf::widget::init

ls $FZF_WIDGET_ROOT/autoload/widgets/ | \
  sed -e 's/fzf-//g' | \
  grep '^docker-.*$' | \
  egrep -v '^select-widget$' | \
  __fzf::widget::select $FZF_WIDGET_OPTS[select-docker-widget] +m

__fzf::widget::filter "sed 's/^/fzf-/'"

__fzf::widget::exec
