#!/bin/zsh

if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  if [[ -n $TMUX ]]; then
    local msg='fzf-git-add-files: Not a git repository'
    tmux split-window "less <<< \"$msg\""
  fi
  return 1
fi

__fzf::widget::init 'git add --'

git status --short | \
  grep '^.[MD?]' | \
  __fzf::widget::select $FZF_WIDGETS_OPTS[git-add-files] -m

__fzf::widget::filter "awk '{print \$2}'"

__fzf::widget::insert
