#!/bin/zsh

__fzf::widget::init 'docker container logs' || return 1

docker container ls -a | \
  sed 1d | \
  __fzf::widget::select $FZF_WIDGET_OPTS[docker-logs-container] +m | \
  awk '{print $1}' | \
  __fzf::widget::insert

__fzf::widget::exec
