#!/bin/zsh

selector-check-command 'ghq'

selector-init 'cd --'

ghq list -p | \
  sort | \
  sed "s|$HOME|~|g" | \
  selector-select +m

selector-cat | sed 's|~|$HOME|g' | selector-save

selector-insert
