#!/bin/zsh

selector-check-command 'lpass'

if ! lpass status -q; then
  if [[ -n $TMUX ]]; then
    private msg='fzf-copy-password: not logged in lpass'
    tmux split-window "less <<< \"$msg\""
  fi
  return 1
fi

selector-init 'lpass show --'

lpass ls | sed -E 's/ \[id: ([0-9]+)\]//' | selector-select +m

selector-insert " | sed -n -E 's/^(Password|Passphrase): //gp' | uniq | xsel -bi"
