#!/bin/zsh

if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  if [[ -n $TMUX ]]; then
    local msg='fzf-git-checkout-branch: Not a git repository'
    tmux split-window "less <<< \"$msg\""
  fi
  return 1
fi

selector-init 'git checkout'

git branch --list -v | \
  grep -v '^\*' | \
  sed 's/^  *//' | \
  selector-select +m

selector-filter "awk '{print \$1}'"

selector-insert
