#!/bin/zsh

__fzf::widget::init 'docker container kill'

docker container ls | \
  sed 1d | \
  __fzf::widget::select $FZF_WIDGET_OPTS[docker-kill-containers] -m

__fzf::widget::filter "awk '{print \$1}'"

__fzf::widget::insert
