#!/bin/zsh

__fzf::widget::check 'cdr' || return 1

__fzf::widget::init 'cd --' || return 1

cdr -l | \
  sed 's/^[^ ][^ ]*  *//' | \
  __fzf::widget::select $FZF_WIDGET_OPTS[change-recent-dir] +m | \
  __fzf::widget::insert -q

__fzf::widget::exec
