#!/bin/zsh

selector-init 'docker container logs'

docker container ls -a | \
  sed 1d | \
  selector-select $FZF_WIDGETS_OPTS[docker-logs-container] +m

selector-filter "awk '{print \$1}'"

selector-insert
