#!/bin/zsh

__fzf::widget::init 'docker volume rm'

docker volume ls | \
  sed 1d | \
  __fzf::widget::select $FZF_WIDGETS_OPTS[docker-remove-volumes] -m

__fzf::widget::filter "awk '{print \$2}'"

__fzf::widget::insert
