#!/bin/zsh

__fzf::widget::init 'cd --' || return 1

hash -d | sed "s/\([^=]*\)/\x1b[34;1m\1\x1b[0m/" | \
  __fzf::widget::select $FZF_WIDGET_OPTS[change-named-directory] +m --ansi | \
  cut -d'=' -f2 | \
  __fzf::widget::insert -q

__fzf::widget::exec
