#!/bin/zsh

selector-init

ls $FZF_WIDGETS_ROOT/autoload/widgets/ | \
  sed -e 's/selector-//g' -e 's/-widget//g' | \
  egrep -v '^select$' | \
  selector-select +m

if [[ -n `cat /tmp/selector` ]]; then
  selector-`cat /tmp/selector`-widget
fi
