#!/bin/zsh

selector-check-command 'lpass'

if ! lpass status -q; then
  if [[ -n $TMUX ]]; then
    private msg='selector-copy-password-widget: not logged in lpass'
    tmux split-window "less <<< \"$msg\""
  fi
  return 1
fi

selector-init 'lpass show'

private -a id=(`lpass ls Develop | sed -E 's/.+\[id: ([0-9]+)\]/\1/'`)

lpass show --name $id | sort | selector-select +m

selector-exec
